import logging
import smtplib
from email.mime.text import MIMEText

import config
import supabase_utils

logger = logging.getLogger(__name__)


def send_email(subject: str, html_body: str) -> bool:
    """Send an HTML email via SMTP with STARTTLS."""
    if not all([config.SMTP_USERNAME, config.SMTP_PASSWORD, config.EMAIL_FROM, config.EMAIL_TO]):
        logger.info("Email not configured — skip notification.")
        return False

    msg = MIMEText(html_body, "html")
    msg["Subject"] = subject
    msg["From"] = config.EMAIL_FROM
    msg["To"] = config.EMAIL_TO

    try:
        with smtplib.SMTP(config.SMTP_SERVER, config.SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(config.SMTP_USERNAME, config.SMTP_PASSWORD)
            server.send_message(msg)
        logger.info(f"Email sent to {config.EMAIL_TO}.")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def _format_job_line(job: dict, idx: int) -> str:
    score = job.get("resume_score", "?")
    title = job.get("job_title", "N/A")
    company = job.get("company", "N/A")
    job_url = job.get("job_url", "")
    link = f' &mdash; <a href="{job_url}">Apply</a>' if job_url else ""
    return f"<tr><td>{idx}.</td><td><b>{title}</b> @ {company}</td><td><b>{score}/100</b></td><td>{link}</td></tr>"


def send_daily_digest(top_n: int = None) -> bool:
    """Fetch top scored jobs and send an email digest."""
    top_n = top_n or getattr(config, "DIGEST_TOP_N", 10)

    jobs = supabase_utils.get_top_scored_jobs_to_apply(top_n)
    if not jobs:
        logger.info("No scored jobs to digest.")
        return False

    rows = "\n".join(_format_job_line(j, i) for i, j in enumerate(jobs, 1))
    html = f"""<html><body style="font-family:sans-serif;">
<h2>Daily Job Digest</h2>
<p>Top {len(jobs)} matching jobs for you:</p>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;">
<tr style="background:#f0f0f0;"><th>#</th><th>Job</th><th>Score</th><th>Link</th></tr>
{rows}
</table>
<p style="color:#888;font-size:12px;">Generated by job-scraper — run the workflow again to refresh.</p>
</body></html>"""

    return send_email("Daily Job Digest — Top Matches", html)
